### ISSUE TITLE
go build error - unable to compile the project

### ISSUE THREAD

**Issue by rayanebel** [Kubedex/helm-controller#5]
Hello,

Thanks for this tool. I would like to test it so I cloned this project on my laptop but when I tried to make a `go build` I have the following issue : `can't load package: package github.com/Kubedex/helm-controller: build constraints exclude all Go files in /Users/xxxxxxxx/xxxxxx/xxxxxxx/helm-controller`. I saw that your are using `go.mod` and I don't see any constraints which can cause this issue. Maybe you can help me to understand why I have this error message ?

For your information, as you are using `go mod` I cloned this project in a local directory outside of my `GOPATH`

Thanks you.

**Comment by gamunu** [comment]
@rayanebel setup the operator sdk cli and then build the image using cli
https://github.com/operator-framework/operator-sdk#install-the-operator-sdk-cli

`operator-sdk build docker.io/{repository}/{image}:{tag}`
